### PR TITLE
Don't charge exp for searching for items (1.14)

### PR DESCRIPTION
**Pull request by jascotty2**
Anvil GUI was charging exp for searching for heads. Fixed that.
:)

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Going to double check this commit, I can't decide if this is gonna break the layout of my files or not.

**Comment by Thatsmusic99** [comment]
To be fair I'm meant to fix the issue with the repo being in a bad folder in a new repo sooner or later when I'm not so busy, and in fact the commit doesn't actually change any of the java files. Did you forget to commit it or?

**Comment by jascotty2** [comment]
Wow, out of habit I added 'src' (a shortcut file for my ide) instead of the main folder xD

**Comment by Thatsmusic99** [comment]
Alright thank you for committing the code that time. Will give it a shot when I get the chance. But no worries, was kind of confused xD

**Comment by Thatsmusic99** [comment]
Tested and confirmed that everything works fine. Am hoping this is possible with the previous versions, but if so I'll do those. Thank you again!

**Pull request merged**
