### PR TITLE
Polish translation for HeadsPlus

### PR DESCRIPTION
**Pull request by Gurbiel**
Translated by Górbiel
Correction by Mistermychciak

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Will check why the Travis-CI build failed then will pull this commit. Thank you to both of you for this!

**Comment by Thatsmusic99** [comment]
Easy fix.

**Comment by Gurbiel** [comment]
If I decide to change some strings  (some were unclear) do I have to just make a new pull request?

**Comment by Thatsmusic99** [comment]
You can just commit it as far as I'm aware. (Make sure you're committing to the pull request though and not the normal master branch)

**Comment by Gurbiel** [comment]
Can you give me the list of all {setting}, bacause Polish is hard to standardize and I'm not sure if I translated this correctly? I'm talking about setValue, addedValue and removedValue.
(I attached an example of one word in English and same word in Polish)
image

**Comment by Gurbiel** [comment]
Ok, I found it and everything seems fine. I think the Polish translation is complete.
If that's not a problem, can you add some credit for this?
Something like this:
//Translated by Górbiel
//Correction by Mistermychciak

**Comment by Thatsmusic99** [comment]
Alright, I was about to double check that myself. And of course I can, I did just add some credit for other translators a while ago too. I'll pull it now unless you say otherwise!

**Comment by Thatsmusic99** [comment]
In fact are there any changes you want to make before I pull this? Just to make sure.

**Comment by Gurbiel** [comment]
No, I think that's all. I'm happy that I could help!

**Pull request merged**
