### PR TITLE
Better resource management, navigation options, fix 1.14 anvil search

### PR DESCRIPTION
**Pull request by jascotty2**
InventoryManager code cleanup
- no longer generates objects for the entire category each time a page is requested
- inventory tracks the actual object used, no needless copies for gc discard
Close open inventories on plugin disable
Added additional navigation buttons, changed titles to show the page they move to
Added dynamic heads listing option for people with large databases - 100+ pages becomes 60+ pages
Fixed anvil search gui for 1.14
Categories and enabled heads are buffered at load time
Heads are buffered on load to decrease lookup time
'Database' option for heads is now optional, defaults true - decreases minimum file size
HeadInventory cleanup
- no longer re-generates head item lore
Fix mysql syntax for new players (' instead of `)

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Good lord, you've been busy cleaning up some of the older, clunkier code for the plugin (considering this was originally my first plugin after all). Now I'm half annoyed at myself for just updating the plugin on Spigot... xD

Although I'll say now this is definitely impressive and a lot nicer on my eyes as well. Will run through the changes made and give it a few shots. Thank you as well for fixing that 1.14 anvil GUI too - there are a few things I have to test with it because in some versions it would close automatically for some reason. I did try and seek help from a fellow developer who had it working himself, but we didn't get that far.

But to sum this up... this is definitely a lot I can learn from, thank you again!

**Comment by jascotty2** [comment]
No problem! Glad to help out :)
I do like this plugin, but it was a bit clunkier than I liked xD

Also, whenever you get a chance, maybe make a repo for SpectateProtection?
I made some fixes to get it working on my server, but I don't have a place to share it with you without sending the code via discord or a stash ;P

**Comment by Thatsmusic99** [comment]
Yeah there are definitely still some areas I need to touch on. I think my next goal is to face my fears with reflection to cut down the plugin's size a bit when setting NBT tags, because setting the same code each time for each version is tiring. However I am a bit more experienced that I was before (it's mostly thanks to working with SimplePets as well so I could cover more areas in plugin development and learn from other developers).

I sure can - SP's one of my older side projects but I can definitely open a repo for that. I'll just need to find the project first and see if I need to clean it up at all...

**Comment by Thatsmusic99** [comment]
Speaking of that I've already got to make a quick update to SpectateProtection - just a fix for the outdated API.

**Comment by Thatsmusic99** [comment]
Alright for some odd reason, Github's not acting nice to me so I can't add the contents of the repo today. I'm not going to be surprised if this was the main reason why I couldn't get HeadsPlus's repo working correctly at first...

**Comment by Thatsmusic99** [comment]
Or not. https://github.com/Thatsmusic99/SpectateProtection/

Have tested this pull request for anything that may need changing, but it's nothing too big, and it seems to work fine with the old icon symbols too. Thank you once again - you're godly!

**Pull request merged**
